### ISSUE TITLE
Publish pre-compiled binaries

### ISSUE THREAD

**Issue by mnil** [google/keep-sorted#37]
To simplify integration it would be nice if there was published release artifacts for popular architectures similar to e.g. bazel/buildtools: https://github.com/bazelbuild/buildtools/releases/tag/v7.1.2

**Comment by AlexanderGH** [comment]
+1. Ideally they could also be signed to avoid Apple's quarantine prompts (though even unsigned would help simplify things).

**Comment by JeffFaer** [comment]
This is entirely reasonable. Ideally we'd have some sort of github workflow setup to do this automatically when we publish a new release. I'm unlikely to have bandwidth to look into this in the near future, so if someone else wants to take a crack at it, that would be greatly appreciated :)

**Comment by AlexanderGH** [comment]
Here you go:
```yaml
name: Publish Release Artifacts

on:
  release:
    types: [prereleased, released, published]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Upload Artifacts to Release
        run: |
          echo Uploading Artifacts For ${{github.event.release.tag_name}}
          gh release upload ${{github.event.release.tag_name}} keep-sorted --clobber
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
```
